services:
  api:
    build: .
    image: gymapi
    container_name: gym-api
    command: uvicorn App.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_BACKEND_URL: redis://redis:6379/0
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - redis
    restart: always
    networks:
      - gym-net

  celery:
    image: gymapi
    container_name: gym-celery
    command: celery -A App.Tasks.task.app_celery worker --loglevel=info --pool=solo
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_BACKEND_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: always
    networks:
      - gym-net

  redis:
    image: redis:alpine
    container_name: gym-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - gym-net

  frontend:
    build: .\Frontend\
    image: frontendgym
    container_name: gym-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always
    networks:
      - gym-net

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: gym-stripe-cli
    command: >
      listen
      --api-key ${STRIPE_SECRET_KEY}
      --forward-to http://api:8000/v1/api/payments/webhook
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - gym-net
    restart: unless-stopped

networks:
  gym-net:
    driver: bridge