[project]
name = "gymbackendapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2",
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "bcrypt>=5.0.0",
    "fastapi-limiter>=0.2.0",
    "fastapi-mail>=1.6.5",
    "fastapi[standard]>=0.138.1",
    "flake8>=7.3.0",
    "gunicorn>=26.0.0",
    "httpx>=0.28.1",
    "imagekitio[aiohttp]>=5.7.0",
    "mysql>=0.0.3",
    "passlib[bcrypt]>=1.7.4",
    "pillow>=12.3.0",
    "pylint>=4.0.6",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "radon>=6.0.1",
    "redis>=8.0.1",
    "sqlalchemy>=2.0.51",
    "stripe>=15.4.0",
]
