"""init tables

Revision ID: a877fc209f10
Revises: 82c2f2ec1c76
Create Date: 2026-09-02 19:12:29.619443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a877fc209f10'
down_revision: Union[str, Sequence[str], None] = '82c2f2ec1c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('MembershipsID', sa.String(length=60), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('walk_machine', sa.Boolean(), nullable=False),
    sa.Column('deduct', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MembershipsID'),
    sa.UniqueConstraint('MembershipsID')
    )
    op.create_table('users',
    sa.Column('UserID', sa.String(length=60), nullable=False),
    sa.Column('UserName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('Role', sa.String(length=45), nullable=False),
    sa.Column('profile_image', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('UserID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classes',
    sa.Column('ClassesID', sa.String(length=60), nullable=False),
    sa.Column('ClassName', sa.String(length=60), nullable=False),
    sa.Column('TypeClass', sa.String(length=60), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Start_time', sa.String(length=60), nullable=False),
    sa.Column('End_time', sa.String(length=60), nullable=False),
    sa.Column('Trainer_id', sa.String(length=60), nullable=False),
    sa.Column('Is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Trainer_id'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('ClassesID'),
    sa.UniqueConstraint('ClassesID')
    )
    op.create_table('subscriptions',
    sa.Column('SubscriptionsID', sa.String(length=60), nullable=False),
    sa.Column('UserID', sa.String(length=60), nullable=False),
    sa.Column('membershipsID', sa.String(length=60), nullable=False),
    sa.Column('StartDate', sa.DateTime(), nullable=False),
    sa.Column('EndDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['membershipsID'], ['memberships.MembershipsID'], ),
    sa.PrimaryKeyConstraint('SubscriptionsID'),
    sa.UniqueConstraint('SubscriptionsID')
    )
    op.create_table('user_profiles',
    sa.Column('UserProfileID', sa.String(length=60), nullable=False),
    sa.Column('UserID', sa.String(length=60), nullable=False),
    sa.Column('Phone', sa.String(length=45), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('gender', sa.String(length=45), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('UserProfileID'),
    sa.UniqueConstraint('UserID'),
    sa.UniqueConstraint('UserProfileID')
    )
    op.create_table('booking',
    sa.Column('BookingID', sa.String(length=60), nullable=False),
    sa.Column('ClassID', sa.String(length=60), nullable=False),
    sa.Column('UserID', sa.String(length=60), nullable=False),
    sa.Column('Is_active', sa.Boolean(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ClassID'], ['classes.ClassesID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID'),
    sa.UniqueConstraint('BookingID')
    )
    op.create_table('payments',
    sa.Column('PaymentsID', sa.String(length=60), nullable=False),
    sa.Column('Subscription_id', sa.String(length=60), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Typepay', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['Subscription_id'], ['subscriptions.SubscriptionsID'], ),
    sa.PrimaryKeyConstraint('PaymentsID'),
    sa.UniqueConstraint('PaymentsID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('booking')
    op.drop_table('user_profiles')
    op.drop_table('subscriptions')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('memberships')
    # ### end Alembic commands ###
