"""move column role in a profile user to table user.

Revision ID: bdd2d28190e8
Revises: 8e75ff44742d
Create Date: 2026-08-03 13:14:42.460438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdd2d28190e8"
down_revision: Union[str, Sequence[str], None] = "8e75ff44742d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "is_active")
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.add_column(
        "user_profiles",
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
